version: '3'

services: 
  node_api:
    build: .
    ports: 
    - "4000:4000"
    environment: 
    - LETSENCRYPT_HOST=node.marcwitney.com
    - VIRTUAL_HOST=node.marcwitney.com
    - LETSENCRYPT_EMAIL=marcwitney@live.com
    - VIRTUAL_PORT=4000
    labels:
      container_group: logging
    logging:
      driver: gelf
      options:
        gelf-address: udp://172.16.0.38:12201
        labels: container_group

networks:
  default:
    external:
      name: monitoring_logging