# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "f5:82:2e:f0:61:7e:2b:0e:5b:74:1e:36:5c:b4:2f:25"
      # run tests!
      - run: yarn test
      - deploy:
          name: digital-ocean
          command: ssh marc@159.203.42.163 cd ~/tilr-node; git pull; docker-compose up --build
      # - deploy:
      #     name: possible
      #     command: |
      #       if [[ "${CIRCLE_BRANCH}" == "*epic*" ]]; then
              # push to our awesome place
      #       fi



